### ISSUE TITLE
Content Pack now Available!

### ISSUE THREAD

**Issue by Zet0rz** [Zet0rz/nZombies-Unlimited#42]
If you want to play the developmental version, you can now play with the content used by the gamemode in its current version.

[Workshop Link](https://steamcommunity.com/sharedfiles/filedetails/?id=1712782641)

This version should be valid all the way up until Stage 1's release, but if there are any errors or missing items, report them here.

**Comment by DjNathann** [comment]
Error pops up when spawning in the map

[ERROR] addons/nzombies-unlimited-master/lua/nzombies-unlimited/core/entities_tools/doors_nzu.lua:304: 'end' expected near 'return'
  1. unknown - addons/nzombies-unlimited-master/lua/nzombies-unlimited/core/entities_tools/doors_nzu.lua:0

**Comment by DjNathann** [comment]
The model of the power panel is missing as there's only the switch.

**Comment by Zet0rz** [comment]
> The model of the power panel is missing as there's only the switch.

Should be fixed in the content pack update

> Error pops up when spawning in the map

This one was fixed in 6cf96e8. (Also bug reports not related to content pack should go in their related issue, or a new issue)

**Comment by Punkinator7** [comment]
- Missing Texture in Version/Legacy Tab in Spawn Menu
- Power switch model still missing

**Comment by Zet0rz** [comment]
> * Missing Texture in Version/Legacy Tab in Spawn Menu

Nice catch, thought I added that but apparently not yet.

> * Power switch model still missing

This was actually a code issue rather than a missing model, the code still attempted to use the old nZombies model path.

**Comment by Punkinator7** [comment]
Ok so for some reason, when I have the content pack installed, the mystery box platform models used for the markers show as errors, but when I don't have the content pack installed, the model shows up fine but you know, everything else would be an error/missing texture. Thinking it's something jank with the content pack.
